In [1]:
import pandas as pd
import numpy as np

In [2]:
# The path to our CSV file
file = "./Resources/open-beer-database.csv"

# Read our Kickstarter data into pandas
df = pd.read_csv(file, encoding= 'unicode_escape')
df.head()

,Name,id,brewery_id,cat_id,style_id,Alcohol By Volume,International Bitterness Units,Standard Reference Method,Universal Product Code,filepath,...,last_mod,Style,Category,Brewer,Address,City,State,Country,Coordinates,Website
0,Porter,716,842,2,25,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,Porter,Irish Ale,McMenamins Mill Creek,13300 Bothell-Everett Highway #304,Mill Creek,Washington,United States,"47.8774, -122.211",NaN
1,Red Truck Ale,622,1237,3,33,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style Amber/Red Ale,North American Ale,Taylor's Crossing Brewing,1025 Marine Drive,North Vancouver,British Columbia,Canada,"49.3238, -123.102",NaN
2,Possession Porter,723,445,2,25,5.6,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,Porter,Irish Ale,Diamond Knot Brewery & Alehouse,621 Front Street,Mukilteo,Washington,United States,"47.9485, -122.305",http://www.diamondknot.com/
3,Firehouse Red,754,504,3,33,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style Amber/Red Ale,North American Ale,Engine House #9,611 North Pine,Tacoma,Washington,United States,"47.256, -122.473",NaN
4,Maibock,736,1124,7,90,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,Traditional German-Style Bock,German Lager,Scuttlebutt Brewing,1524 West Marine View Drive,Everett,Washington,United States,"47.9975, -122.214",NaN

In [3]:
us_beer = df.loc[df['Country'] == 'United States']
us_beer

,Name,id,brewery_id,cat_id,style_id,Alcohol By Volume,International Bitterness Units,Standard Reference Method,Universal Product Code,filepath,...,last_mod,Style,Category,Brewer,Address,City,State,Country,Coordinates,Website
0,Porter,716,842,2,25,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,Porter,Irish Ale,McMenamins Mill Creek,13300 Bothell-Everett Highway #304,Mill Creek,Washington,United States,"47.8774, -122.211",NaN
2,Possession Porter,723,445,2,25,5.6,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,Porter,Irish Ale,Diamond Knot Brewery & Alehouse,621 Front Street,Mukilteo,Washington,United States,"47.9485, -122.305",http://www.diamondknot.com/
3,Firehouse Red,754,504,3,33,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style Amber/Red Ale,North American Ale,Engine House #9,611 North Pine,Tacoma,Washington,United States,"47.256, -122.473",NaN
4,Maibock,736,1124,7,90,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,Traditional German-Style Bock,German Lager,Scuttlebutt Brewing,1524 West Marine View Drive,Everett,Washington,United States,"47.9975, -122.214",NaN
5,Buzz Beer,2079,809,3,26,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style Pale Ale,North American Ale,Mad Crab Restaurant and Brewery,NaN,Strongsville,Ohio,United States,"41.3145, -81.8357",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967,Big Eye IPA,2447,68,3,31,6.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style India Pale Ale,North American Ale,Ballast Point Brewing,5401 Linda Vista Road #406,San Diego,California,United States,"32.7668, -117.195",http://www.ballastpoint.com/
5968,Pale Ale,2672,734,3,26,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style Pale Ale,North American Ale,Keg Microbrewery & Restaurant,NaN,Stevens Point,Wisconsin,United States,"44.5236, -89.5746",NaN
5969,Blonde Ale,2841,483,1,10,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,English-Style Pale Mild Ale,British Ale,Egan Brewing,NaN,De Pere,Wisconsin,United States,"44.4489, -88.0604",NaN
5970,Steinworthy Oktoberfest,2868,483,7,84,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,German-Style Oktoberfest,German Lager,Egan Brewing,NaN,De Pere,Wisconsin,United States,"44.4489, -88.0604",NaN
5972,Zwickel,2969,907,8,95,0.0,0.0,0.0,0.0,NaN,...,2010-07-22 16:00:00-04:00,American-Style Lager,North American Lager,New Glarus Brewing Company,2400 State Highway 69,New Glarus,Wisconsin,United States,"42.8171, -89.6306",http://www.newglarusbrewing.com/

In [4]:
us_beer = us_beer[['Name','id','Alcohol By Volume','International Bitterness Units','Standard Reference Method', 'Style',  
                 'Category', 'Brewer', 'City', 'State', 'Coordinates'
                 ]]
us_beer

,Name,id,Alcohol By Volume,International Bitterness Units,Standard Reference Method,Style,Category,Brewer,City,State,Coordinates
0,Porter,716,0.0,0.0,0.0,Porter,Irish Ale,McMenamins Mill Creek,Mill Creek,Washington,"47.8774, -122.211"
2,Possession Porter,723,5.6,0.0,0.0,Porter,Irish Ale,Diamond Knot Brewery & Alehouse,Mukilteo,Washington,"47.9485, -122.305"
3,Firehouse Red,754,0.0,0.0,0.0,American-Style Amber/Red Ale,North American Ale,Engine House #9,Tacoma,Washington,"47.256, -122.473"
4,Maibock,736,0.0,0.0,0.0,Traditional German-Style Bock,German Lager,Scuttlebutt Brewing,Everett,Washington,"47.9975, -122.214"
5,Buzz Beer,2079,0.0,0.0,0.0,American-Style Pale Ale,North American Ale,Mad Crab Restaurant and Brewery,Strongsville,Ohio,"41.3145, -81.8357"
...,...,...,...,...,...,...,...,...,...,...,...
5967,Big Eye IPA,2447,6.0,0.0,0.0,American-Style India Pale Ale,North American Ale,Ballast Point Brewing,San Diego,California,"32.7668, -117.195"
5968,Pale Ale,2672,0.0,0.0,0.0,American-Style Pale Ale,North American Ale,Keg Microbrewery & Restaurant,Stevens Point,Wisconsin,"44.5236, -89.5746"
5969,Blonde Ale,2841,0.0,0.0,0.0,English-Style Pale Mild Ale,British Ale,Egan Brewing,De Pere,Wisconsin,"44.4489, -88.0604"
5970,Steinworthy Oktoberfest,2868,0.0,0.0,0.0,German-Style Oktoberfest,German Lager,Egan Brewing,De Pere,Wisconsin,"44.4489, -88.0604"
5972,Zwickel,2969,0.0,0.0,0.0,American-Style Lager,North American Lager,New Glarus Brewing Company,New Glarus,Wisconsin,"42.8171, -89.6306"

In [6]:
us_beer_df = us_beer.dropna(how = 'any')

In [7]:
us_beer_df['Region'] = ''

In [8]:
northeast = ['Maine', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New Hampshire', 'Vermont', 'New York', 'Pennsylvania', 'New Jersey', 'Delaware', 'Maryland']
southeast = ['West Virginia', 'Virginia', 'Kentucky', 'Tennessee', 'North Carolina', 'South Carolina', 'Georgia', 'Alabama', 'Mississippi', 'Arkansas', 'Louisiana', 'Florida']
midwest = ['Ohio', 'Indiana', 'Michigan', 'Illinois', 'Missouri', 'Wisconsin', 'Minnesota', 'Iowa', 'Kansas', 'Nebraska', 'South Dakota', 'North Dakota']
southwest = ['Texas', 'Oklahoma', 'New Mexico', 'Arizona']
west = ['Colorado', 'Wyoming', 'Montana', 'Idaho', 'Washington', 'Oregon', 'Utah', 'Nevada', 'California', 'Alaska', 'Hawaii']

In [11]:
us_beer_df['Region'] = np.where(us_beer_df['State'].isin(northeast), 'Northeast',
                      np.where(us_beer_df['State'].isin(southeast), 'Southeast',
                      np.where(us_beer_df['State'].isin(midwest), 'Midwest',
                      np.where(us_beer_df['State'].isin(southwest), 'Southwest',
                      np.where(us_beer_df['State'].isin(west), 'West',
                      'Unknown')))))

In [15]:
beer_df = us_beer_df.loc[us_beer_df['Alcohol By Volume'] != 0]
beer_df

,Name,id,Alcohol By Volume,International Bitterness Units,Standard Reference Method,Style,Category,Brewer,City,State,Coordinates,Region
2,Possession Porter,723,5.6,0.0,0.0,Porter,Irish Ale,Diamond Knot Brewery & Alehouse,Mukilteo,Washington,"47.9485, -122.305",West
6,Free Bike Amber,742,4.5,0.0,0.0,American-Style Amber/Red Ale,North American Ale,Skagit River Brewing,Mount Vernon,Washington,"48.4192, -122.335",West
19,Potrero ESB,3982,5.2,0.0,0.0,Special Bitter or Best Bitter,British Ale,21st Amendment Brewery Cafe,San Francisco,California,"37.7825, -122.393",West
23,Twisted Kilt Scotch Ale,4221,5.0,0.0,0.0,Scotch Ale,British Ale,Thirsty Dog Brewing,Akron,Ohio,"41.0689, -81.5172",Midwest
29,HarvestÃƒÂ¶r Fresh Hop Ale,5243,7.2,0.0,0.0,American-Style Pale Ale,North American Ale,Lift Bridge Brewery,Stillwater,Minnesota,"45.0565, -92.8222",Midwest
...,...,...,...,...,...,...,...,...,...,...,...,...
5948,Unearthly Imperial India Pale Ale,4884,11.0,0.0,0.0,Imperial or Double India Pale Ale,North American Ale,Southern Tier Brewing Co,Lakewood,New York,"42.1008, -79.3357",Northeast
5950,Richbrau India Pale Ale,5231,6.2,0.0,0.0,American-Style India Pale Ale,North American Ale,Richbrau Brewing Company,Richmond,Virginia,"37.5356, -77.4338",Southeast
5951,Dubble Fantasy,5310,5.0,0.0,0.0,Other Belgian-Style Ales,Belgian and French Ale,San Diego Brewing,San Diego,California,"32.7922, -117.099",West
5957,"Double Eagle ""High-Test"" Scotch Ale",3429,8.0,0.0,0.0,Scotch Ale,British Ale,Pinehurst Village Brewery,Aberdeen,North Carolina,"35.1315, -79.4295",Southeast
5967,Big Eye IPA,2447,6.0,0.0,0.0,American-Style India Pale Ale,North American Ale,Ballast Point Brewing,San Diego,California,"32.7668, -117.195",West

In [17]:
beer_df.to_csv("./output_data/craft_beer.csv", index=False, header=True)